# Pandas Learning

In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1={
    "name":["Rajnsih","Tanish","Shivansh"],
    "marks":["92","95","94"]
}

In [3]:
dict1

{'name': ['Rajnsih', 'Tanish', 'Shivansh'], 'marks': ['92', '95', '94']}

In [4]:
df=pd.DataFrame(dict1)

In [5]:
df.to_csv("rajnish.csv",index=False)

In [6]:
df.head(1)

      name marks
0  Rajnsih    92

In [7]:
df.tail(1)

       name marks
2  Shivansh    94

In [8]:
df.describe()

           name marks
count         3     3
unique        3     3
top     Rajnsih    92
freq          1     1

In [9]:
df.max()

name     Tanish
marks        95
dtype: str

In [10]:
df.min()

name     Rajnsih
marks         92
dtype: str

In [11]:
rajnish=pd.read_csv("rajnish.csv")

In [12]:
rajnish

       name  marks
0   Rajnsih     92
1    Tanish     95
2  Shivansh     94

In [13]:
rajnish

       name  marks
0   Rajnsih     92
1    Tanish     95
2  Shivansh     94

In [14]:
rajnish.index=["1","2","3"]

In [15]:
rajnish

       name  marks
1   Rajnsih     92
2    Tanish     95
3  Shivansh     94

In [16]:
rajnish.to_csv("rajnish.csv")

In [17]:
newf=pd.DataFrame(np.random.rand(4,5),index=np.arange(4))

In [18]:
newf

          0         1         2         3         4
0  0.101610  0.308675  0.218748  0.131652  0.575945
1  0.882886  0.196165  0.426438  0.421545  0.603920
2  0.784348  0.743141  0.486074  0.607578  0.033418
3  0.997499  0.311837  0.880689  0.612960  0.850092

In [19]:
newf[0]

0    0.101610
1    0.882886
2    0.784348
3    0.997499
Name: 0, dtype: float64

In [20]:
type(newf)

pandas.DataFrame

In [21]:
type(newf[0])

pandas.Series

In [22]:
newf.T

          0         1         2         3
0  0.101610  0.882886  0.784348  0.997499
1  0.308675  0.196165  0.743141  0.311837
2  0.218748  0.426438  0.486074  0.880689
3  0.131652  0.421545  0.607578  0.612960
4  0.575945  0.603920  0.033418  0.850092

In [23]:
newf1=newf.copy()

In [24]:
newf1

          0         1         2         3         4
0  0.101610  0.308675  0.218748  0.131652  0.575945
1  0.882886  0.196165  0.426438  0.421545  0.603920
2  0.784348  0.743141  0.486074  0.607578  0.033418
3  0.997499  0.311837  0.880689  0.612960  0.850092

In [25]:
newf.loc[0,0]=12

In [26]:
newf

           0         1         2         3         4
0  12.000000  0.308675  0.218748  0.131652  0.575945
1   0.882886  0.196165  0.426438  0.421545  0.603920
2   0.784348  0.743141  0.486074  0.607578  0.033418
3   0.997499  0.311837  0.880689  0.612960  0.850092

In [27]:
newf1.loc[0,0]=22

In [28]:
newf1

           0         1         2         3         4
0  22.000000  0.308675  0.218748  0.131652  0.575945
1   0.882886  0.196165  0.426438  0.421545  0.603920
2   0.784348  0.743141  0.486074  0.607578  0.033418
3   0.997499  0.311837  0.880689  0.612960  0.850092

In [29]:
newf

           0         1         2         3         4
0  12.000000  0.308675  0.218748  0.131652  0.575945
1   0.882886  0.196165  0.426438  0.421545  0.603920
2   0.784348  0.743141  0.486074  0.607578  0.033418
3   0.997499  0.311837  0.880689  0.612960  0.850092

In [30]:
newf.columns=list("ABCDE")

In [31]:
newf

           A         B         C         D         E
0  12.000000  0.308675  0.218748  0.131652  0.575945
1   0.882886  0.196165  0.426438  0.421545  0.603920
2   0.784348  0.743141  0.486074  0.607578  0.033418
3   0.997499  0.311837  0.880689  0.612960  0.850092

In [32]:
newf.loc[0,"A"]=28

In [33]:
newf

           A         B         C         D         E
0  28.000000  0.308675  0.218748  0.131652  0.575945
1   0.882886  0.196165  0.426438  0.421545  0.603920
2   0.784348  0.743141  0.486074  0.607578  0.033418
3   0.997499  0.311837  0.880689  0.612960  0.850092

In [34]:
newf.drop("E",axis=1)

           A         B         C         D
0  28.000000  0.308675  0.218748  0.131652
1   0.882886  0.196165  0.426438  0.421545
2   0.784348  0.743141  0.486074  0.607578
3   0.997499  0.311837  0.880689  0.612960

In [35]:
newf.loc[[1,2],["A","B"]]

          A         B
1  0.882886  0.196165
2  0.784348  0.743141

In [36]:
newf.loc[:,["A","B"]]

           A         B
0  28.000000  0.308675
1   0.882886  0.196165
2   0.784348  0.743141
3   0.997499  0.311837

In [37]:
newf.loc[[1,2],:]

          A         B         C         D         E
1  0.882886  0.196165  0.426438  0.421545  0.603920
2  0.784348  0.743141  0.486074  0.607578  0.033418

In [38]:
newf.loc[(newf["A"]<0.8) & (newf["E"]>0.4)]

Empty DataFrame
Columns: [A, B, C, D, E]
Index: []

In [39]:
newf.iloc[0,3]

np.float64(0.13165230430687447)

In [40]:
newf.iloc[0,3]

np.float64(0.13165230430687447)

In [41]:
newf

           A         B         C         D         E
0  28.000000  0.308675  0.218748  0.131652  0.575945
1   0.882886  0.196165  0.426438  0.421545  0.603920
2   0.784348  0.743141  0.486074  0.607578  0.033418
3   0.997499  0.311837  0.880689  0.612960  0.850092

In [42]:
newf.iloc[[0,1],[2,3]]

          C         D
0  0.218748  0.131652
1  0.426438  0.421545

In [43]:
newf.reset_index()

   index          A         B         C         D         E
0      0  28.000000  0.308675  0.218748  0.131652  0.575945
1      1   0.882886  0.196165  0.426438  0.421545  0.603920
2      2   0.784348  0.743141  0.486074  0.607578  0.033418
3      3   0.997499  0.311837  0.880689  0.612960  0.850092

In [44]:
newf.reset_index(drop=True)

           A         B         C         D         E
0  28.000000  0.308675  0.218748  0.131652  0.575945
1   0.882886  0.196165  0.426438  0.421545  0.603920
2   0.784348  0.743141  0.486074  0.607578  0.033418
3   0.997499  0.311837  0.880689  0.612960  0.850092

In [45]:
newf.info

<bound method DataFrame.info of            A         B         C         D         E
0  28.000000  0.308675  0.218748  0.131652  0.575945
1   0.882886  0.196165  0.426438  0.421545  0.603920
2   0.784348  0.743141  0.486074  0.607578  0.033418
3   0.997499  0.311837  0.880689  0.612960  0.850092>

In [47]:
df.value_counts(dropna=False)

name      marks
Rajnsih   92       1
Tanish    95       1
Shivansh  94       1
Name: count, dtype: int64

In [48]:
newf.notnull()

      A     B     C     D     E
0  True  True  True  True  True
1  True  True  True  True  True
2  True  True  True  True  True
3  True  True  True  True  True

In [49]:
newf.isnull()

       A      B      C      D      E
0  False  False  False  False  False
1  False  False  False  False  False
2  False  False  False  False  False
3  False  False  False  False  False

In [50]:
newf.mean()

A    7.666183
B    0.389955
C    0.502987
D    0.443434
E    0.515844
dtype: float64

In [51]:
newf.median()

A    0.940193
B    0.310256
C    0.456256
D    0.514562
E    0.589933
dtype: float64